language: php

php:
  - 5.4

env:
  - APP=openpsa

before_script:
  - ./Ragnaroek/travis_midgard.sh
  - cd Ragnaroek && wget -q http://getcomposer.org/composer.phar
  - php composer.phar install --dev
  - ./tests/travis_${APP}.sh
  - phpenv config-add tests/midgard2_${APP}.ini

script: phpunit -c tests/phpunit_${APP}.xml.dist

notifications:
    irc: "irc.freenode.org#midgard"
