language: php

php:
  - 5.3
  - 5.4

before_script:
  - ./Ragnaroek/travis_midgard.sh
  - cd Ragnaroek && wget -q http://getcomposer.org/composer.phar
  - cd Ragnaroek && php composer.phar install --dev

script: cd Ragnaroek && php -c midgard2.ini `which phpunit` -c tests/phpunit.xml.dist

notifications:
    irc: "irc.freenode.org#midgard"
